theme: jekyll-theme-minimal
title: Does Diversity Pay Off?
description: Examining the relation between characteristics of movies and their box office revenue with an emphasis on factors like diversity and gender
#remote_theme: pages-themes/architect@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one
