theme: jekyll-theme-minimal
title: Does Diversity Pay Off?
description: Examining the relation between characteristics of movies and their box office revenue with an emphasis on factors like diversity and gender
