theme: jekyll-theme-cayman
title: Does diversity pay off?
description: Examining the relation between characteristics of movies and their box office revenue with an emphasis on factors like diversity and gender
