#theme: jekyll-theme-minimal
title: b0bEast Datastory
description: First prototype of simple website
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
