theme: jekyll-theme-cayman
title: Does diversity pay off?
description: Examining the relation between characteristics of movies and their box office revenue with an emphasis on diversity factors like ethncitiy, age, and gender