theme: jekyll-theme-minimal
#remote_theme: pages-themes/architect@v0.2.0
title: b0bEast Datastory
description: First prototype of simple website
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
